default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root  
  password: password    
  host: 127.0.0.1       
  port: 3306
  socket: /tmp/mysql.sock      

development:
  <<: *default
  database: blog_dev_db 

test:
  <<: *default
  database: blog_test_db       